name: Deploy Lambda
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  call-backend-deploy-workflow:
    uses: WilliamShimizu/aws-infra-fe-be-init/.github/workflows/backend-template.yaml@main
    with:
      region: us-west-2
    secrets:
      inherit
