name: Deploy Lambda
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      region:
        required: true
        type: string
    secrets:
      DEPLOYMENT_ROLE:
        required: true
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
        role-session-name: GHActions-${{ github.sha }}
        aws-region: ${{ inputs.region }}

    - name: Package and deploy Lambdas
      run: |
        LAMBDA_NAME=aws-infra-fe-be-init-lambda-${{ inputs.region }}-${{ inputs.stage }}
        LAMBDA_REGION=${{ inputs.region }}
        bash packaging.bash $LAMBDA_NAME $LAMBDA_REGION
