name: Deploy CDK Stack
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  push:
    branches:
      - dev
    paths:
      - 'infra/**'
      - '.github/workflows/infra-dev.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  
    - name: Set up Node for npm
        uses: actions/setup-node@v3
        with:
          node-version: "16"

    - name: Install infra python requirements, cdk
      run: |
        cd infra
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g aws-cdk

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
        role-session-name: GHActions-${{ github.sha }}
        aws-region: us-west-2

    - name: Deploy CDK Stack
      run: cdk deploy --all --require-approval never
