name: Deploy CDK Stack

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
        role-session-name: GHActions-${{ github.sha }}
        aws-region: us-west-2

    - name: Deploy CDK Stack
      run: cdk deploy --all --require-approval never
